version: '3.9'

services:
  mysqldb:
    image: mysql:8.3
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  spring-api1:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/skyio_db?createDatabaseIfNotExist=true
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_ROOT_PASSWORD}
      - spring.datasource.driver-class-name=${MYSQLDB_DRIVER}
      - token=${SECRET_TOKEN}
      - SMTP_HOST= ${SMTP_HOST}
      - SMTP_USER= ${SMTP_USER}
      - SMTP_PWD= ${SMTP_PWD}
      - spring.mail.port=587
      - spring.jpa.defer-datasource-initialization=true
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enable=true
      - spring.jpa.show-sql=false
      - spring.h2.console.enabled=false
      - spring.sql.init.platform=mysql
      - logging.level.org.apache.kafka=ERROR
      - spring.sql.init.mode=always

  spring-api2:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/skyio_db?createDatabaseIfNotExist=true
      - spring.datasource.username=${MYSQL_USER}
      - spring.datasource.password=${MYSQL_PASSWORD}
      - spring.datasource.driver-class-name=${MYSQLDB_DRIVER}
      - token=${SECRET_TOKEN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PWD=${SMTP_PWD}
      - spring.mail.port=587
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enable=true
      - spring.sql.init.platform=mysql
      - logging.level.org.apache.kafka=ERROR
      - spring.jpa.show-sql=false
      - spring.h2.console.enabled=false

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api1
      - spring-api2
    ports:
      - "8080:8080"